//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlikhohang
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class N11_QLNguyenLieuNhaHang_T5Entities : DbContext
    {
        public N11_QLNguyenLieuNhaHang_T5Entities()
            : base("name=N11_QLNguyenLieuNhaHang_T5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BienBanThanhLy> BienBanThanhLies { get; set; }
        public virtual DbSet<ChiTietBBTL> ChiTietBBTLs { get; set; }
        public virtual DbSet<ChiTietHDN> ChiTietHDNs { get; set; }
        public virtual DbSet<ChiTietPDNL> ChiTietPDNLs { get; set; }
        public virtual DbSet<ChiTietPTK> ChiTietPTKs { get; set; }
        public virtual DbSet<HoaDonNhapNL> HoaDonNhapNLs { get; set; }
        public virtual DbSet<NguyenLieu> NguyenLieux { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhieuDatNL> PhieuDatNLs { get; set; }
        public virtual DbSet<PhieuThongKe> PhieuThongKes { get; set; }
    
        public virtual ObjectResult<GetAllNL_Result> GetAllNL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllNL_Result>("GetAllNL");
        }
    }
}
