//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_ly_nhan_su
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLiNhanSuEntities : DbContext
    {
        public QuanLiNhanSuEntities()
            : base("name=QuanLiNhanSuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaoHiem> BaoHiems { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<HopDong> HopDongs { get; set; }
        public virtual DbSet<Luong> Luongs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TrinhDoHV> TrinhDoHVs { get; set; }
    
        [DbFunction("QuanLiNhanSuEntities", "DanhsachNV")]
        public virtual IQueryable<DanhsachNV_Result> DanhsachNV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<DanhsachNV_Result>("[QuanLiNhanSuEntities].[DanhsachNV]()");
        }
    
        public virtual int changeSalary(string ma, Nullable<int> luongCB, Nullable<double> heso, Nullable<double> hesophucap, Nullable<double> bhyt, Nullable<double> bhtn, Nullable<double> bhxh)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            var luongCBParameter = luongCB.HasValue ?
                new ObjectParameter("luongCB", luongCB) :
                new ObjectParameter("luongCB", typeof(int));
    
            var hesoParameter = heso.HasValue ?
                new ObjectParameter("heso", heso) :
                new ObjectParameter("heso", typeof(double));
    
            var hesophucapParameter = hesophucap.HasValue ?
                new ObjectParameter("hesophucap", hesophucap) :
                new ObjectParameter("hesophucap", typeof(double));
    
            var bhytParameter = bhyt.HasValue ?
                new ObjectParameter("bhyt", bhyt) :
                new ObjectParameter("bhyt", typeof(double));
    
            var bhtnParameter = bhtn.HasValue ?
                new ObjectParameter("bhtn", bhtn) :
                new ObjectParameter("bhtn", typeof(double));
    
            var bhxhParameter = bhxh.HasValue ?
                new ObjectParameter("bhxh", bhxh) :
                new ObjectParameter("bhxh", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("changeSalary", maParameter, luongCBParameter, hesoParameter, hesophucapParameter, bhytParameter, bhtnParameter, bhxhParameter);
        }
    
        public virtual int DeleteEmployee(string tenNV)
        {
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("tenNV", tenNV) :
                new ObjectParameter("tenNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteEmployee", tenNVParameter);
        }
    
        public virtual int DeleteOffice(string tenPB)
        {
            var tenPBParameter = tenPB != null ?
                new ObjectParameter("tenPB", tenPB) :
                new ObjectParameter("tenPB", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteOffice", tenPBParameter);
        }
    
        public virtual int EditEmployee(string tenNV, string tenPB, string tenCV, Nullable<int> luong, string quequan)
        {
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("tenNV", tenNV) :
                new ObjectParameter("tenNV", typeof(string));
    
            var tenPBParameter = tenPB != null ?
                new ObjectParameter("TenPB", tenPB) :
                new ObjectParameter("TenPB", typeof(string));
    
            var tenCVParameter = tenCV != null ?
                new ObjectParameter("TenCV", tenCV) :
                new ObjectParameter("TenCV", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("luong", luong) :
                new ObjectParameter("luong", typeof(int));
    
            var quequanParameter = quequan != null ?
                new ObjectParameter("quequan", quequan) :
                new ObjectParameter("quequan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditEmployee", tenNVParameter, tenPBParameter, tenCVParameter, luongParameter, quequanParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
